stages:
  - test
  - build
  - upload
  - release

variables:
  # Package version can only contain numbers (0-9), and dots (.).
  # Must be in the format of X.Y.Z, i.e. should match /\A\d+\.\d+\.\d+\z/ regular expresion.
  # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rust-ping-log"

unit-test:
  stage: test
  image: registry.gitlab.com/wrenger/rust-ping-log
  script:
    - rustc --version
    - cargo test

build-frontend:
  stage: build
  image: node
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd ping-view
    - npm install && npm run-script build
  artifacts:
    paths:
      - ping-view/build/

build-backend:
  stage: build
  image: registry.gitlab.com/wrenger/rust-ping-log
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release --target=aarch64-unknown-linux-gnu
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/ping-log

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mkdir bin && cp target/aarch64-unknown-linux-gnu/release/ping-log bin/ping-$CI_COMMIT_TAG-aarch64
    - mkdir bin/ping-view && mv ping-view/build bin/ping-view
    - tar -acf ping-$CI_COMMIT_TAG-aarch64.tar.gz bin/ping-view bin/ping-$CI_COMMIT_TAG-aarch64
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ping-$CI_COMMIT_TAG-aarch64.tar.gz ${PACKAGE_REGISTRY_URL}/$CI_COMMIT_TAG/ping-$CI_COMMIT_TAG-aarch64.tar.gz

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"ping-$CI_COMMIT_TAG-aarch64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/$CI_COMMIT_TAG/ping-$CI_COMMIT_TAG-aarch64.tar.gz\"}"
