[package]
name = "ping-log"
version = "0.3.1"
authors = ["Lars Wrenger <lars@wrenger.net>"]
description = "Simple RESTful webserver for logging and visualizing network access times."
repository = "https://gitlab.com/wrenger/rust-ping-log"
keywords = ["ping", "log", "webserver", "REST"]
categories = ["webserver"]
readme = "README.md"
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
actix-web = "3.3"
actix-files = "0.5"
chrono = "0.4"
serde = "1.0"
structopt = "0.3"
regex = "1.5"
lazy_static = "1.4"
libc = "0.2"
