[package]
name = "rust-ping-log"
version = "0.2.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]
description = "Simple RESTful webserver for logging and visualizing network access times."
repository = "https://gitlab.com/l4r0x/rust-ping-log"
keywords = ["ping", "log", "webserver", "REST"]
categories = ["webserver"]
readme = "README.md"
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
chrono = "0.4"
serde = "1.0"
structopt = "0.3"
actix-web = "2.0"
actix-files = "0.2"
actix-rt = "1.0"
