[package]
name = "rust-ping-log"
version = "0.1.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]

[dependencies]
hyper = "0.12.9"
futures = "0.1.23"
serde_json = "1.0.26"
chrono = "0.4.6"
argparse = "0.2.2"
serde = "1.0.76"
serde_derive = "1.0.76"
