[package]
name = "rust-ping-log"
version = "0.2.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]
description = "Simple RESTful webserver for logging and visualizing network access times."
repository = "https://gitlab.com/wrenger/rust-ping-log"
keywords = ["ping", "log", "webserver", "REST"]
categories = ["webserver"]
readme = "README.md"
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
actix-web = "3.3"
chrono = "0.4"
num_cpus = "1.13"
serde = "1.0"
structopt = "0.3"
regex = "1.4"
lazy_static = "1.4.0"

[build-dependencies]
base64 = "0.13"
regex = "1.4"
