[package]
name = "rust-ping-log"
version = "0.2.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]

[dependencies]
actix-web = "1.0"
actix-files = "0.1.4"
argparse = "0.2.2"
chrono = "0.4.7"
serde = "1.0.98"
