[package]
name = "rust-ping-log"
version = "0.2.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
serde = "1.0.103"
structopt = "0.3.5"
actix-web = "1.0"
actix-files = "0.1.7"
